### ISSUE TITLE
Add Downloader

### ISSUE THREAD

**Issue by aqnya** [Moe-hacker/moe-container#11]
Have you ever considered adding a downloader similar to tmoe for this project?

**Comment by Moe-hacker** [comment]
Yes, you can get binary for arm64/x86_64 devices in Release page now.

**Comment by lin1328** [comment]
> Yes, you can get binary for arm64/x86_64 devices in Release page now.

Thank you for adding the download feature. Although I also tried automatic compilation, it seems I can only compile x86_64. Later, when I tried compiling arm64, due to an operational error and loss of the submitted source code, I eventually gave up on automatic compilation
