### ISSUE TITLE
Submit to Debian Repository

### ISSUE THREAD

**Issue by dabao1955** [Moe-hacker/moe-container#15]
Hello, I am very interested in this project, and I plan to try to submit ruri to the official repository of Debian.

If you agree, I will fork a copy as a downstream and make the following changes:
- Use autoconf instead of handwritten configure and Makefile
- Modify the contents of the debian folder to comply with the debian package submission specification
- Remove .clang-format file
- Modify README
- Other things like this will be added later.

Finally, thank you for creating and open-sourcing such a wonderful software.

**Comment by Moe-hacker** [comment]
> Hello, I am very interested in this project, and I plan to try to submit ruri to the official repository of Debian.
> 
> If you agree, I will fork a copy as a downstream and make the following changes:
> - Use autoconf instead of handwritten configure and Makefile
> - Modify the contents of the debian folder to comply with the debian package submission specification
> - Remove .clang-format file
> - Modify README
> - Other things like this will be added later.
> 
> Finally, thank you for creating and open-sourcing such a wonderful software.

I'm very happy that you like my project. Feel free to make any changes you need; that's exactly why I chose the MIT License😉
