### ISSUE TITLE
Assertion 'path_is_absolute(p)' failed at src/basic/chase.c:566, function chase(). Aborting.

### ISSUE THREAD

**Issue by Xynonners** [Moe-hacker/moe-container#6]
First off, thank you for this great project. I have a working PID1 init chroot container now (after some service mods).

However, systemd-tmpfiles & udevd v254+ seems to suffer from the same issue as fakechroot as seen here:

https://github.com/systemd/systemd/issues/28458#issuecomment-1708448441

**Comment by Moe-hacker** [comment]
Thanks for your report, but I have no idea to fix it. It seems that systemd doesn't like to run in containers, you will find that in some cases, systemd can not work properly even in docker containers . In my test, it even made my desktop crash when I try to run it in a privileged container.
I used centos rootfs for test ( I can't start systemd in ubuntu containers )
```shell
sudo ./ruri -D
sudo ./ruri -u --keep cap_sys_admin --keep cap_mknod ../centos /lib/systemd/systemd --unit=basic.target
```
and `systemctl status` was like:
```log
Failed to dump process list for 'moe-studio', ignoring: Input/output error
● moe-studio
    State: degraded
    Units: 160 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 1 units
    Since: Wed 2023-10-04 10:45:27 UTC; 5s ago
  systemd: 252-15.el9
   CGroup: /
```
At least  `systemctl start`  works, but seems that all default services were died.

**Comment by Xynonners** [comment]
mmm, fakechroot seems to have fixed it with this patch https://gitlab.archlinux.org/archlinux/packaging/packages/fakechroot/-/commit/3a161d61dfbf532e98f8e6f3de0b0b93c77aaa26 that wraps statx?

In my case I'm not exactly trying to run the entirety of systemd inside a container, only certain parts of it that chimera linux uses to function (init is dinit). udevd / other systemd-linked projects also seem to run into this (chroot path expansion?) issue, though downgrading to <=253 fixes them (currently I'm bypassing the issue by overwriting the binaries via /usr/local).

**Comment by Moe-hacker** [comment]
> mmm, fakechroot seems to have fixed it with this patch https://gitlab.archlinux.org/archlinux/packaging/packages/fakechroot/-/commit/3a161d61dfbf532e98f8e6f3de0b0b93c77aaa26 that wraps statx?
> 
> In my case I'm not exactly trying to run the entirety of systemd inside a container, only certain parts of it that chimera linux uses to function (init is dinit). udevd / other systemd-linked projects also seem to run into this (chroot path expansion?) issue, though downgrading to <=253 fixes them (currently I'm bypassing the issue by overwriting the binaries via /usr/local).

ruri is a real chroot container, so I think it is different from fakechroot that creates a faked environment. It takes the same effect as unshare+capsh in most cases. I built it for devices that can't run docker for some reasons, but if you can, it's better to use container like docker.

**Comment by Moe-hacker** [comment]
I have find the definition of path_is_absolute() at [/src/basic/path-util.h](https://github.com/systemd/systemd/blob/27a1719bbae776deb3fa6f4c39f29ddfb19efd38/src/basic/path-util.h#L43) 
It's very simple:
```C
static inline bool path_is_absolute(const char *p) {
        if (!p) /* A NULL pointer is definitely not an absolute path */
                return false;

        return p[0] == '/';
}
```
I don't know how it fails.
'path_is_absolute(p)' failed at src/basic/chase.c:566 might means [this line](https://github.com/systemd/systemd/blob/27a1719bbae776deb3fa6f4c39f29ddfb19efd38/src/basic/chase.c#L584)
Not sure how to fix this

**Comment by Xynonners** [comment]
> > mmm, fakechroot seems to have fixed it with this patch https://gitlab.archlinux.org/archlinux/packaging/packages/fakechroot/-/commit/3a161d61dfbf532e98f8e6f3de0b0b93c77aaa26 that wraps statx?
> > In my case I'm not exactly trying to run the entirety of systemd inside a container, only certain parts of it that chimera linux uses to function (init is dinit). udevd / other systemd-linked projects also seem to run into this (chroot path expansion?) issue, though downgrading to <=253 fixes them (currently I'm bypassing the issue by overwriting the binaries via /usr/local).
> 
> ruri is a real chroot container, so I think it is different from fakechroot that creates a faked environment. It takes the same effect as unshare+capsh in most cases. I built it for devices that can't run docker for some reasons, but if you can, it's better to use container like docker.

Yeah, I'm currently using ruri since docker/lxc requires a lot more kernel features that android (fustratingly) doesn't enable. Another one of my goals is to also recompile the kernel to support these features, but due to gki I have to rebuild all 4 partitions (boot, vendor_boot, vendor_dlkm, dtbo) which I'm pretty scared to do with sn undocumented build harness.

Even then, I'd probably stick to ruri since I'm bind-mounting /tmp to termux-x11's tmp.

**Comment by Xynonners** [comment]
> I have find the definition of path_is_absolute() at [/src/basic/path-util.h](https://github.com/systemd/systemd/blob/27a1719bbae776deb3fa6f4c39f29ddfb19efd38/src/basic/path-util.h#L43) It's very simple:
> 
> ```c
> static inline bool path_is_absolute(const char *p) {
>         if (!p) /* A NULL pointer is definitely not an absolute path */
>                 return false;
> 
>         return p[0] == '/';
> }
> ```
> 
> I don't know how it fails. 'path_is_absolute(p)' failed at src/basic/chase.c:566 might means [this line](https://github.com/systemd/systemd/blob/27a1719bbae776deb3fa6f4c39f29ddfb19efd38/src/basic/chase.c#L584) Not sure how to fix this

Maybe we can diff 253/254 and see what changed around there?

**Comment by Moe-hacker** [comment]
> > I have find the definition of path_is_absolute() at [/src/basic/path-util.h](https://github.com/systemd/systemd/blob/27a1719bbae776deb3fa6f4c39f29ddfb19efd38/src/basic/path-util.h#L43) It's very simple:
> > ```c
> > static inline bool path_is_absolute(const char *p) {
> >         if (!p) /* A NULL pointer is definitely not an absolute path */
> >                 return false;
> > 
> >         return p[0] == '/';
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't know how it fails. 'path_is_absolute(p)' failed at src/basic/chase.c:566 might means [this line](https://github.com/systemd/systemd/blob/27a1719bbae776deb3fa6f4c39f29ddfb19efd38/src/basic/chase.c#L584) Not sure how to fix this
> 
> Maybe we can diff 253/254 and see what changed around there?

There's too many files changed, but I found [this commit](https://github.com/systemd/systemd/commit/0d68cd72b602edac05b4ae5d17a65ae828e61ff4) though I don't know what it did.
Seems that the bug in fakechroot has already been fixed, but I can't use the same way to fix it up, so that nothing I can help.

**Comment by Moe-hacker** [comment]
I think 87183526f440fb0545b91a3d61f99c5ae06992b1 might fixed this, though I don't know why.
If I bind-mount `/` in the container:
```
[root@localhost ~]# mount --bind / /
[root@localhost ~]# /usr/bin/systemd-sysusers
Assertion 'path_is_absolute(p)' failed at src/basic/chase.c:648, function chase(). Aborting.
Aborted
[root@localhost ~]# umount /
[root@localhost ~]# /usr/bin/systemd-sysusers
[root@localhost ~]#
```
but seems that bind-mount container_dir outside the container (before chroot()) will not cause this.

**Comment by Xynonners** [comment]
yup, seems to have been fixed for some reason.
now though (3.0.0dev), a service seems to have issues writing to /proc/sys/kernel/hostname, though it probably wasn't supposed to be able to do that anyway.

now the only remaining issue I have is with running elogind which gives a cgroups permission denied error.

**Comment by Moe-hacker** [comment]
> yup, seems to have been fixed for some reason.
> now though (3.0.0dev), a service seems to have issues writing to /proc/sys/kernel/hostname, though it probably wasn't supposed to be able to do that anyway.

/proc/sys is mounted as read-only by default.
You can try `mount -t proc proc /proc` to re-mount /proc in privileged containers(With CAP_SYS_ADMIN) to fix this.
