### ISSUE TITLE
Nesting namespaces?

### ISSUE THREAD

**Issue by Xynonners** [Moe-hacker/moe-container#7]
I was wondering if there was a way to nest namespaces using ruri? (use unshare within the container)

Currently, when tried it gives a permission denied error.

**Comment by Xynonners** [comment]
Also, is it possible to passthrough the /dev/dri render devices aswell (sorry for all the q)

It seems like mounting anything in /dev gets overridden due to the way things operate.

**Comment by Moe-hacker** [comment]
> I was wondering if there was a way to nest namespaces using ruri? (use unshare within the container)
> 
> Currently, when tried it gives a permission denied error.

Unshare(2) needs cap_sys_admin capability,  which is disabled for security purposes by default. 
You should give the container cap_sys_admin to run unshare(2) in it, just add `--keep cap_sys_admin` argument.

**Comment by Moe-hacker** [comment]
> Also, is it possible to passthrough the /dev/dri render devices aswell (sorry for all the q)
> 
> It seems like mounting anything in /dev gets overridden due to the way things operate.

For security purposes, I only want to keep the basic devices visible in containers. You can add the argument `--keep cap_mknod` and create the missing devices manually in containers.

**Comment by Moe-hacker** [comment]
> Also, is it possible to passthrough the /dev/dri render devices aswell (sorry for all the q)
> 
> It seems like mounting anything in /dev gets overridden due to the way things operate.

In the kernel docs:
```
226 char	Direct Rendering Infrastructure (DRI)
		  0 = /dev/dri/card0		First graphics card
		  1 = /dev/dri/card1		Second graphics card
```
So you can
```
mkdir /dev/dri
mknod /dev/dri/card0 c 226 0
mknod /dev/dri/card1 c 226 1
```

**Comment by Xynonners** [comment]
> > I was wondering if there was a way to nest namespaces using ruri? (use unshare within the container)
> > Currently, when tried it gives a permission denied error.
> 
> Unshare(2) needs cap_sys_admin capability, which is disabled for security purposes by default. You should give the container cap_sys_admin to run unshare(2) in it, just add `--keep cap_sys_admin` argument.

alright, added to:
`ruri --keep cap_sys_admin -u /data/chimera`
but unshare spits out:
`unshare: unshare failed: Operation not permitted`
strace says it fails at:
`unshare(CLONE_NEWUSER) = -1 EPERM (Operation not permitted)`

**Comment by Xynonners** [comment]
also, another question but how do you pass through cgroups?

**Comment by Moe-hacker** [comment]
> > > I was wondering if there was a way to nest namespaces using ruri? (use unshare within the container)
> > > Currently, when tried it gives a permission denied error.
> > 
> > Unshare(2) needs cap_sys_admin capability, which is disabled for security purposes by default. You should give the container cap_sys_admin to run unshare(2) in it, just add `--keep cap_sys_admin` argument.
> 
> alright, added to:
> `ruri --keep cap_sys_admin -u /data/chimera`
> but unshare spits out:
> `unshare: unshare failed: Operation not permitted`
> strace says it fails at:
> `unshare(CLONE_NEWUSER) = -1 EPERM (Operation not permitted)`

Seems that user namespace cannot be used in chroot containers.
https://serverfault.com/questions/135599/ubuntu-can-non-root-user-run-process-in-chroot-jail/648637#648637
